# Generated by Django 5.1 on 2024-09-18 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_service_alter_images_image_servicebooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Blog Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Blog Slug')),
                ('body', models.TextField(verbose_name='Main Body')),
                ('is_accepted', models.BooleanField(verbose_name='Blog accepted')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By The User')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
