# Generated by Django 5.1 on 2024-09-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to=None, verbose_name='Blog Thumbnail'),
            preserve_default=False,
        ),
    ]
